server {
    listen 5173;
    root /usr/share/nginx/html;
    index index.html;

    location /gestao-ti/ {
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
