server {
    listen 5177;
    root /usr/share/nginx/html;
    index index.html;

    location /entregas/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
